version: '2'

services:
  master:
    build:
      context: ./ros
    container_name: ros_master
    ports:
      - "11311:11311"
      - "9090:9090"
    volumes:
      - roslogs:/root/.ros/log/
      - ./ros/src:/ros_ws/src
    command: /bin/bash -c "source /ros_ws/devel/setup.bash && roslaunch vrep_unity_raven2 main.launch"

volumes:
  roslogs: